const all_product = [
  { id: 1, name: "Floral V-Neck Blouse", category: "women", image: "product_1.png", new_price: 50.0, old_price: 80.5 },
  { id: 2, name: "Ruffled Sleeve Casual Top", category: "women", image: "product_2.png", new_price: 85.0, old_price: 120.5 },
  { id: 3, name: "Chiffon Wrap Blouse", category: "women", image: "product_3.png", new_price: 60.0, old_price: 100.5 },
  { id: 4, name: "Peplum Hem Button Shirt", category: "women", image: "product_4.png", new_price: 100.0, old_price: 150.0 },
  { id: 5, name: "Lace Panel Elegant Blouse", category: "women", image: "product_5.png", new_price: 85.0, old_price: 120.5 },
  { id: 6, name: "Polka Dot V-Neck Top", category: "women", image: "product_6.png", new_price: 85.0, old_price: 120.5 },
  { id: 7, name: "Embroidered Summer Top", category: "women", image: "product_7.png", new_price: 85.0, old_price: 120.5 },
  { id: 8, name: "Sleeveless Pleated Blouse", category: "women", image: "product_8.png", new_price: 85.0, old_price: 120.5 },
  { id: 9, name: "Boho Flowy Tunic", category: "women", image: "product_9.png", new_price: 85.0, old_price: 120.5 },
  { id: 10, name: "Silk Drape Neck Top", category: "women", image: "product_10.png", new_price: 85.0, old_price: 120.5 },
  { id: 11, name: "Balloon Sleeve Blouse", category: "women", image: "product_11.png", new_price: 85.0, old_price: 120.5 },
  { id: 12, name: "Button Front Linen Shirt", category: "women", image: "product_12.png", new_price: 85.0, old_price: 120.5 },
  { id: 13, name: "Olive Green Bomber Jacket", category: "men", image: "product_13.png", new_price: 85.0, old_price: 120.5 },
  { id: 14, name: "Black Zippered Track Jacket", category: "men", image: "product_14.png", new_price: 85.0, old_price: 120.5 },
  { id: 15, name: "Navy Slim Fit Blazer", category: "men", image: "product_15.png", new_price: 85.0, old_price: 120.5 },
  { id: 16, name: "Denim Bomber Jacket", category: "men", image: "product_16.png", new_price: 85.0, old_price: 120.5 },
  { id: 17, name: "Tan Faux Leather Jacket", category: "men", image: "product_17.png", new_price: 85.0, old_price: 120.5 },
  { id: 18, name: "Charcoal Sports Jacket", category: "men", image: "product_18.png", new_price: 85.0, old_price: 120.5 },
  { id: 19, name: "Quilted Winter Jacket", category: "men", image: "product_19.png", new_price: 85.0, old_price: 120.5 },
  { id: 20, name: "Puffer Hooded Jacket", category: "men", image: "product_20.png", new_price: 85.0, old_price: 120.5 },
  { id: 21, name: "Classic Fit Denim Jacket", category: "men", image: "product_21.png", new_price: 85.0, old_price: 120.5 },
  { id: 22, name: "Zip-Front Moto Jacket", category: "men", image: "product_22.png", new_price: 85.0, old_price: 120.5 },
  { id: 23, name: "Urban Utility Jacket", category: "men", image: "product_23.png", new_price: 85.0, old_price: 120.5 },
  { id: 24, name: "Fleece-Lined Hoodie Jacket", category: "men", image: "product_24.png", new_price: 85.0, old_price: 120.5 },
  { id: 25, name: "Kids Orange Hoodie", category: "kid", image: "product_25.png", new_price: 85.0, old_price: 120.5 },
  { id: 26, name: "Kids Blue Striped Sweatshirt", category: "kid", image: "product_26.png", new_price: 85.0, old_price: 120.5 },
  { id: 27, name: "Kids Red Full Zip Hoodie", category: "kid", image: "product_27.png", new_price: 85.0, old_price: 120.5 },
  { id: 28, name: "Kids Black Sport Sweatshirt", category: "kid", image: "product_28.png", new_price: 85.0, old_price: 120.5 },
  { id: 29, name: "Kids Yellow Patch Hoodie", category: "kid", image: "product_29.png", new_price: 85.0, old_price: 120.5 },
  { id: 30, name: "Kids Green Pullover Hoodie", category: "kid", image: "product_30.png", new_price: 85.0, old_price: 120.5 },
  { id: 31, name: "Kids Navy Zip Sweatshirt", category: "kid", image: "product_31.png", new_price: 85.0, old_price: 120.5 },
  { id: 32, name: "Kids Grey Full Sleeve Hoodie", category: "kid", image: "product_32.png", new_price: 85.0, old_price: 120.5 },
  { id: 33, name: "Kids White Printed Hoodie", category: "kid", image: "product_33.png", new_price: 85.0, old_price: 120.5 },
  { id: 34, name: "Kids Pink Fleece Hoodie", category: "kid", image: "product_34.png", new_price: 85.0, old_price: 120.5 },
  { id: 35, name: "Kids Beige Cozy Hoodie", category: "kid", image: "product_35.png", new_price: 85.0, old_price: 120.5 },
  { id: 36, name: "Kids Teal Knit Hoodie", category: "kid", image: "product_36.png", new_price: 85.0, old_price: 120.5 },
];

module.exports = all_product;
